CREATE TABLE "GCG_5351_OBS_PART"(
 "TERMINAL" CHAR(3),
 "REPORT_ID" CHAR(10),
 "LAST_USE" CHAR(10),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "DESCRIPTION" CHAR(30),
 "PL" CHAR(2),
 "UNIT_COST" CHAR(15),
 "QTY_ONHAND" CHAR(15),
 "EXTENSION" CHAR(15));